# Generated by Django 3.2.7 on 2021-10-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_alter_patient_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
